# [o3] - Proyecto Ozono -ETL_Estaciones- v1

### [.0] CLUSTERING KMEANS

### [.1] -> 2014-18 | [.2] ->2019-NOW

#Origenes

Aire : https://datos.madrid.es/portal/site/egob/menuitem.c05c1f754a33a9fbe4b2e4b284f1a5a0/?vgnextoid=9e42c176313eb410VgnVCM1000000b205a0aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD&vgnextfmt=default

Tiempo: https://datos.madrid.es/sites/v/index.jsp?vgnextoid=2ac5be53b4d2b610VgnVCM2000001f4a900aRCRD&vgnextchannel=374512b9ace9f310VgnVCM100000171f5a0aRCRD

## [0] - Librerias

In [79]:
from __future__ import print_function
import findspark
findspark.init('/home/rulicering/BigData/spark-2.4.5-bin-hadoop2.7')
from pyspark.sql import SparkSession
import pandas as pd
from pyspark.sql.types import StructField,StringType,IntegerType,StructType,FloatType
from pyspark.ml.clustering import KMeans
from pyspark.ml.feature import VectorAssembler

#AEMET
import time
import swagger_client
from swagger_client.rest import ApiException
from pprint import pprint
import datetime
import requests,json
import re as reg

## [1] - Inicializar sesión de Spark

In [80]:
spark = SparkSession.builder.appName('estaciones_2019').getOrCreate()

## [2] - ESTACIONES CONTROL AIRE (Ayunt. Madrid)

In [81]:
# https://datos.madrid.es/egob/catalogo/212629-0-estaciones-control-aire.xls

In [82]:
pd_aire = pd.read_excel("https://datos.madrid.es/egob/catalogo/212629-0-estaciones-control-aire.xls")

In [83]:
#pd_aire.head(5)

In [84]:
pd_aire = pd_aire[['CODIGO_CORTO', 'ESTACION', 'DIRECCION', 'ALTITUD','LONGITUD', 'LATITUD']]
#pd_aire["MIDE_AIRE"] = 1 // Te lo mete como float
#pd_aire.LATITUD= pd_aire.LATITUD.round(6)
#pd_aire.LONGITUD= pd_aire.LONGITUD.round(6)
pd_aire.insert(6,"MIDE_AIRE",1)

In [85]:
print("Número de estaciones medición calidad del aire: %d" % pd_aire["ESTACION"].count())

for elem in pd_aire[["CODIGO_CORTO", "ESTACION"]].values.tolist():
    print(elem)

Número de estaciones medición calidad del aire: 24
[4, 'Pza. de España']
[8, 'Escuelas Aguirre']
[11, 'Avda. Ramón y Cajal']
[16, 'Arturo Soria']
[17, 'Villaverde']
[18, 'Farolillo']
[24, 'Casa de Campo']
[27, 'Barajas Pueblo']
[35, 'Pza. del Carmen']
[36, 'Moratalaz']
[38, 'Cuatro Caminos']
[39, 'Barrio del Pilar']
[40, 'Vallecas']
[47, 'Mendez Alvaro']
[48, 'Castellana']
[49, 'Parque del Retiro']
[50, 'Plaza Castilla']
[54, 'Ensanche de Vallecas']
[55, 'Urb. Embajada']
[56, 'Pza. Elíptica']
[57, 'Sanchinarro']
[58, 'El Pardo']
[59, 'Juan Carlos I']
[60, 'Tres Olivos']

## [3.2] -  ESTACIONES CONTROL METEOROLÓGICO (Ayunt. Madrid)

In [86]:
#https://datos.madrid.es/egob/catalogo/300360-0-meteorologicos-estaciones.xls

In [87]:
pd_tiempo = pd.read_excel("https://datos.madrid.es/egob/catalogo/300360-0-meteorologicos-estaciones.xls")

In [88]:
pd_tiempo = pd_tiempo[['CÓDIGO_CORTO', 'ESTACIÓN', 'DIRECCIÓN', 'ALTITUD','LONGITUD', 'LATITUD']]
#pd_tiempo["MIDE_CLIMA"] = 1 #Te lo mete como float
#pd_tiempo.LATITUD= pd_tiempo.LATITUD.round(6)
#pd_tiempo.LONGITUD= pd_tiempo.LONGITUD.round(6)
pd_tiempo.insert(6,"MIDE_CLIMA",1)

In [89]:
#Modificamos los nombres de las columnas -> sin tildes para que cuadre luego al hacer el join
pd_tiempo = pd_tiempo.rename(columns = {"CÓDIGO_CORTO" : "CODIGO_CORTO",'ESTACIÓN': 'ESTACION', 'DIRECCIÓN':'DIRECCION'})

In [90]:
print("Número de estaciones medición clima: %d" % pd_tiempo["ESTACION"].count())

for elem in pd_tiempo[["CODIGO_CORTO", "ESTACION"]].values.tolist():
    print(elem)

Número de estaciones medición clima: 26
[4, 'Plaza España']
[8, 'Escuelas Aguirre']
[16, 'Arturo Soria']
[18, 'Farolillo']
[24, 'Casa de Campo']
[35, 'Plaza del Carmen']
[36, 'Moratalaz']
[38, 'Cuatro Caminos']
[39, 'Barrio del Pilar']
[54, 'Ensanche de Vallecas']
[56, 'Plaza Elíptica']
[58, 'El Pardo']
[59, 'Juan Carlos I']
[102, 'J.M.D. Moratalaz']
[103, 'J.M.D. Villaverde']
[104, 'E.D.A.R. La China']
[106, 'Centro Mpal. De Acústica']
[107, 'J.M.D. Hortaleza']
[108, 'Peñagrande']
[109, 'J.M.D.Chamberí']
[110, 'J.M.D.Centro']
[111, 'J.M.D.Chamartin']
[112, 'J.M.D.Vallecas 1']
[113, 'J.M.D.Vallecas 2']
[114, 'Matadero 01']
[115, 'Matadero 02']

## [4.1] - AYUNTAMIENTO = AIRE

In [91]:
pd_estaciones_ayunt_1 = pd_aire

## [4.2] - MERGE - AYUNTAMIENTO

In [92]:
#pd_final = pd_aire.join(pd_tiempo,lsuffix = "_aire",rsuffix = "_tiempo", on =["CODIGO_CORTO"], how = "outer", sort = True) 
#No tienen el mismo tipo las columnas de Código corto en ambos datasets

pd_estaciones_ayunt_2 = pd_aire.merge(pd_tiempo, on =['CODIGO_CORTO', 'ESTACION', 'DIRECCION', 'ALTITUD', 'LONGITUD', 'LATITUD'], how = "outer")

In [93]:
#pd_estaciones_ayunt_2["CODIGO_CORTO"].count()

## [5.2] - ELIMINAMOS DUPLICADOS

In [94]:
pd_estaciones_ayunt_2.duplicated(["CODIGO_CORTO"])
pd_estaciones_ayunt_2 = pd_estaciones_ayunt_2.drop_duplicates(["CODIGO_CORTO"],keep='first')

In [95]:
#pd_estaciones_ayunt_2["CODIGO_CORTO"].count()

## [6.2] - NULL -> 0

In [96]:
pd_estaciones_ayunt_2 = pd_estaciones_ayunt_2.fillna(0)
pd_estaciones_ayunt_2["MIDE_CLIMA"] = pd_estaciones_ayunt_2["MIDE_CLIMA"].round(1).astype(int)
pd_estaciones_ayunt_2["MIDE_AIRE"] = pd_estaciones_ayunt_2["MIDE_AIRE"].round(1).astype(int)

## [7] - ESTACIONES CONTROL METEOROLÓGICO (AEMET)

In [97]:
configuration = swagger_client.Configuration()
configuration.api_key['api_key'] = 'eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcm95ZWN0by5vem9uby5jb250YWN0QGdtYWlsLmNvbSIsImp0aSI6ImNlZDZiZWQ2LTUyN2EtNGQ2Yi1iOGMyLWU1YmRlNzk3YzYzZSIsImlzcyI6IkFFTUVUIiwiaWF0IjoxNTg2NzE3MTE2LCJ1c2VySWQiOiJjZWQ2YmVkNi01MjdhLTRkNmItYjhjMi1lNWJkZTc5N2M2M2UiLCJyb2xlIjoiIn0.U3b4ELAg-9eJcwgpzr4QgkF-Yj6jb9gw0DOa8sqAwHo'

In [98]:
api_valores = swagger_client.ValoresClimatologicosApi(swagger_client.ApiClient(configuration))

In [99]:
try:
    api_response = api_valores.inventario_de_estaciones__valores_climatolgicos_()
    #print(api_response)
except ApiException as e:
    print("Exception: %s\n" % e)

In [100]:
r = requests.get(api_response.datos)
data = r.content

In [101]:
def data_to_sparkdf(data):
    #Encoding "ISO-8859"
    data_v = data.decode(encoding ='ISO-8859-15')
    data_v0 = data_v
    # Clean the data
    # Step 0 
    for i in range(20):
        if(data_v0[i]=='{'):
            data_v0 = data_v0[i:]
    for i in range(20):
        if(data_v0[-i]=='}'):
            data_v0 = data_v0[:-i+1]
    # Step 1     
    data_v1 = data_v0
    data_v1 = data_v1.replace("\n", "")
    
    # Step 2
    data_v2 = data_v1.replace("},","}},")
    
    # Step 3
    patron =['\s\s','\s"','"\s','\s{']
    replace = [' ','"','"','{']
    
    data_v3 = data_v2
    for i in range(len(patron)):
        data_v3 = reg.sub(patron[i],replace[i],data_v3)

    # Step 4
    data_v4 = data_v3.replace("\",\"","\";\"")
    
    # Step 5
    data_cleaned = data_v4.split("},")

    # String to List of dictionaries
    diccionarios = []
    for fila in data_cleaned:
        #print(fila)
        keys = []
        values = []
        for pareja in fila[1:-1].split(';'):
            #print("Pareja= ",pareja)
            elems =pareja.split(':')
            #print("Elementos= ",elems)
            keys.append(elems[0][1:-1])
            values.append(elems[1][1:-1])
        diccionarios.append(dict(zip(keys,values)))

    # Schema for the new DF
    data_schema = [StructField('latitud',StringType(), True), #Tercer argumento = nullable
                   StructField('provincia', StringType(), True),
                   StructField('altitud', StringType(), True),
                   StructField('indicativo', StringType(), True),
                   StructField('nombre', StringType(), True),
                   StructField('indsinop', StringType(), True),
                   StructField('longitud', StringType(), True)                    
                  ]
    # Create and return the new DF
    return spark.createDataFrame(diccionarios,schema = StructType(data_schema))

In [102]:
df = data_to_sparkdf(data)

In [117]:
pd_estaciones_aemet = df.filter(df["PROVINCIA"]=="MADRID").orderBy("indsinop").toPandas()

In [118]:
def degrees_to_decimal(elem):
    elem = reg.sub('N|E','1',elem)
    elem = reg.sub('S|W','-1',elem)
    return (float(elem[6:])* (float(elem[0:2]) + float(elem[2:4])/60 + float(elem[4:6])/3600))

In [119]:
pd_estaciones_aemet["DIRECCION"] = pd_estaciones_aemet["nombre"]+ "-" + pd_estaciones_aemet["provincia"]
#pd_mad["MIDE_CLIMA_AEMET"] = 1
pd_estaciones_aemet.insert(7,"MIDE_CLIMA_AEMET",1)
pd_estaciones_aemet["LONGITUD"] = [degrees_to_decimal(elem) for elem in pd_estaciones_aemet["longitud"]]
pd_estaciones_aemet["LATITUD"] = [degrees_to_decimal(elem) for elem in pd_estaciones_aemet["latitud"]]

In [121]:
pd_estaciones_aemet = pd_estaciones_aemet[["indsinop","nombre","DIRECCION","altitud","LONGITUD","LATITUD","MIDE_CLIMA_AEMET"]]
pd_estaciones_aemet = pd_estaciones_aemet.rename(columns = {"indsinop":"CODIGO_CORTO",
                                  "nombre": "ESTACION",
                                  "altitud": "ALTITUD"})

In [122]:
pd_estaciones_aemet["CODIGO_CORTO"] = pd_estaciones_aemet["CODIGO_CORTO"].astype(str).astype(int)
pd_estaciones_aemet["ALTITUD"] = pd_estaciones_aemet["ALTITUD"].astype(str).astype(int)

In [123]:
#pd_estaciones_aemet

## [!] -  Descartar las estaciones que estén fuera del area de madrid ciudad

In [124]:
import math
def haversine(p0,p1):
    p0_lat,p0_long =p0.split(',')
    
    lat1, lon1 = round(float(p0_lat),6),round(float(p0_long),6)
    lat2, lon2 = round(float(p1[0]),6),round(float(p1[1]),6)
    
    rad=math.pi/180
    dlat=lat2-lat1
    dlon=lon2-lon1
    R=6372.795477598
    a=(math.sin(rad*dlat/2))**2 + math.cos(rad*lat1)*math.cos(rad*lat2)*(math.sin(rad*dlon/2))**2
    distancia=2*R*math.asin(math.sqrt(a))
    return distancia

plaza_españa = df_estaciones_ayunt.filter(df_estaciones_ayunt["CODIGO_CORTO"]==4).select("LATITUD","LONGITUD")
plaza_españa = plaza_españa.collect()[0]
centro_de_madrid = [40.4165,-3.702561]

plaza_españa_r=[round(plaza_españa[0],6),round(plaza_españa[1],6)]

print("Plaza españa= ", plaza_españa_r[0] , "- ",  plaza_españa_r[1])
print("Madrid= ", centro_de_madrid)

haversine(centro_de_madrid,plaza_españa_r)

In [125]:
# Radio madrid ciudad 15km (PARDO)
pd_estaciones_aemet["LAT_LONG"]= round(pd_estaciones_aemet["LATITUD"],6).astype(str) +','+ round(pd_estaciones_aemet["LONGITUD"],6).astype(str)
centro_de_madrid = [40.4165,-3.702561]
pd_estaciones_aemet["MADRID_CIUDAD"] = [1 if haversine(x,centro_de_madrid) <= 15 else 0 for x in (pd_estaciones_aemet["LAT_LONG"])]
#pd_estaciones_aemet["DISTC_MADRID_CIUDAD"] = [haversine(x,centro_de_madrid) for x in (pd_estaciones_aemet["LAT_LONG"])]

In [126]:
df_estaciones_aemet= spark.createDataFrame(pd_estaciones_aemet)
df_estaciones_aemet= df_estaciones_aemet.filter(df_estaciones_aemet["MADRID_CIUDAD"]== 1).select('CODIGO_CORTO', 'ESTACION', 'DIRECCION', 'ALTITUD', 'LONGITUD','LATITUD', 'MIDE_CLIMA_AEMET')

In [127]:
pd_estaciones_aemet = df_estaciones_aemet.toPandas()

In [128]:
pd_estaciones_aemet.head(10)

,CODIGO_CORTO,ESTACION,DIRECCION,ALTITUD,LONGITUD,LATITUD,MIDE_CLIMA_AEMET
0,8220,"MADRID, CIUDAD UNIVERSITARIA","MADRID, CIUDAD UNIVERSITARIA-MADRID",664,-3.724167,40.451667,1
1,8221,MADRID AEROPUERTO,MADRID AEROPUERTO-MADRID,609,-3.555556,40.466667,1
2,8222,"MADRID, RETIRO","MADRID, RETIRO-MADRID",667,-3.678056,40.411944,1
3,8223,"MADRID, CUATRO VIENTOS","MADRID, CUATRO VIENTOS-MADRID",690,-3.786111,40.375556,1
4,8224,GETAFE,GETAFE-MADRID,620,-3.722222,40.299444,1

##  [8.1] - MERGE AYUNT-AEMET

In [129]:
#pd_estaciones_ayunt.dtypes

In [130]:
#pd_estaciones_aemet.dtypes

In [131]:
pd_estaciones_1 = pd_estaciones_ayunt_1.merge(pd_estaciones_aemet,how='outer')
pd_estaciones_1 = pd_estaciones_1.fillna(0)

##  [8.2] - MERGE AYUNT-AEMET

In [132]:
pd_estaciones_2 = pd_estaciones_ayunt_2.merge(pd_estaciones_aemet,how='outer')
pd_estaciones_2 = pd_estaciones_2.fillna(0)

## [!!.1] - COLUMNA MIDE_CLIMA _FINAL = MIDE_CLIMA_AEMET

In [133]:
pd_estaciones_1["MIDE_CLIMA_FINAL"] = pd_estaciones_1["MIDE_CLIMA_AEMET"]

In [134]:
#pd_estaciones.head(5)

## [!!.2] - COLUMNA MIDE_CLIMA _FINAL = MIDE_CLIMA (AYUNT) + MIDE_CLIMA_AEMET

In [135]:
pd_estaciones_2["MIDE_CLIMA_FINAL"] = pd_estaciones_2["MIDE_CLIMA"] + pd_estaciones_2["MIDE_CLIMA_AEMET"]

## [FUNC] - CLUSTERING

In [153]:
def clustering(selected_k,df_estaciones):
    for i in range(0,selected_k-2): 
        #Vamos de más grupos a menos(mínimo 2). Si no es valido con 10, probamos con 9.. 
        num_cluster = selected_k - i
        #print("NUMERO DE CLUSTERS: ", num_cluster)

        #Crea la agrupación
        kmeans = KMeans(featuresCol='features',k=num_cluster,seed=1,maxIter=40)
        df_estaciones_model = kmeans.fit(df_estaciones)
        df = df_estaciones_model.transform(df_estaciones)

        #Se agrupa por predicción y se valida
        agrupado = df.select("prediction","MIDE_AIRE","MIDE_CLIMA_FINAL").groupBy("prediction").sum().orderBy("prediction")

        """ GRUPO ES VALIDO SI:
                1. El valor de valido > 0 (Hay estaciones de aire y de clima)
                2. El valor de valido == 0 & valido_con_descartables > 0 (solo hay estaciones de clima)
                    * SOLO NOS INTERESAN LAS ESTACIONES DE MEDICIÓN DE AIRE.
                    * Ese grupo luego se descarta
        """  

        agrupado = agrupado.select("prediction","sum(MIDE_AIRE)","sum(MIDE_CLIMA_FINAL)")
        #Sacamos columna "VALIDO":
        # VALIDO >0 implica que en ese grupo hay tanto estaciones de aire como de clima
        # VALIDO == 0 implica que en ese grupo NO hay estaciones de ambos tipos.
        agrupado = agrupado.withColumn("VALIDO",agrupado["sum(MIDE_AIRE)"]*agrupado["sum(MIDE_CLIMA_FINAL)"])
        #agrupado.show()

        #Sacamos la coluna "VALIDO_CON_DESCARTABLES"
        #VALIDO_CON_DESCARTABLES > 0 implica que ese grupo no es VALIDO pero solo hay estaciones de clima
        #VALIDO_CON_DESCARTABLES == 0 implica que ese grupo no es VALIDO y SI hay estaciones de aire. 
        agrupado = agrupado.withColumn("VALIDO_CON_DESCARTABLES", agrupado["sum(MIDE_CLIMA_FINAL)"]+agrupado["VALIDO"])
        #agrupado.show()

        no_validos = [int(row[0]) for row in agrupado.select("prediction").filter(agrupado["VALIDO_CON_DESCARTABLES"]== 0).collect()]
        #print("NO VALIDOS", no_validos)

        valido = (len(no_validos)==0)
        #print("ES VALIDO: ", valido)

        if(valido == 1):
            descartables = [int(row[0]) for row in agrupado.select("prediction").filter(agrupado["VALIDO"]== 0).collect()]
            agrupado.filter(~agrupado["prediction"].isin(descartables)).show()
            df = df.filter(~df["prediction"].isin(descartables))
            break
        #print("="*200)
    return df

## [9.1] - CLUSTERING

In [146]:
df_estaciones_1 = spark.createDataFrame(pd_estaciones_1)
vec_assembler_1 = VectorAssembler(inputCols =["LATITUD","LONGITUD"],outputCol='features')
df_estaciones_1 = vec_assembler_1.transform(df_estaciones_1)

In [147]:
df_estaciones = df_estaciones_1

#SI QUEREMOS ELEGIR UNA K INICIAL (SELECTED_K)
variaciones = []
errores = []
anterior = 0
for i in range(2,df_estaciones.count()):
    kmeans = KMeans(featuresCol='features',k=i,maxIter=30)
    df_estaciones_model = kmeans.fit(df_estaciones)
    wssse = df_estaciones_model.computeCost(df_estaciones)
    errores.append(wssse)
    variaciones.append(wssse-anterior)
    anterior = wssse
    #print("K= ",i ," Within Set Sum of Squared Errors = " + str(wssse))

#1 grado == 118 km
#Seleccionamos la k para la cual el error es menor de 1km
i=0
selected_k = -1
for elem in errores:
    distancia = elem*118
    print(i, " - ", distancia)
    if(distancia < 1): 
        selected_k= i 
        break
    i= i+1

In [148]:
selected_k = df_estaciones.count()

#variaciones
errores
#Cuando baja menos que antes
bajada_anterior = 0
selected_k = -1

for i in range(1,len(errores)):
    if((errores[i-1]-errores[i])<bajada_anterior):
        selected_k = i-1
        break
    else:
        bajada_anterior = errores[i]-errores[i-1]
print(selected_k)

In [154]:
df_1 = clustering(selected_k,df_estaciones)

+----------+--------------+---------------------+------+-----------------------+
|prediction|sum(MIDE_AIRE)|sum(MIDE_CLIMA_FINAL)|VALIDO|VALIDO_CON_DESCARTABLES|
+----------+--------------+---------------------+------+-----------------------+
|         0|          11.0|                  1.0|  11.0|                   12.0|
|         1|           4.0|                  1.0|   4.0|                    5.0|
|         2|           1.0|                  1.0|   1.0|                    2.0|
|         3|           5.0|                  1.0|   5.0|                    6.0|
|         4|           3.0|                  1.0|   3.0|                    4.0|
+----------+--------------+---------------------+------+-----------------------+

In [155]:
pd_estaciones_14_18 = df_1.toPandas()[["CODIGO_CORTO","ESTACION","LATITUD", "LONGITUD","prediction","MIDE_AIRE","MIDE_CLIMA_AEMET","MIDE_CLIMA_FINAL"]].sort_values(by="prediction")
pd_estaciones_14_18 = pd_estaciones_14_18.rename(columns={"prediction":"GRUPO"})
pd_estaciones_14_18

,CODIGO_CORTO,ESTACION,LATITUD,LONGITUD,GRUPO,MIDE_AIRE,MIDE_CLIMA_AEMET,MIDE_CLIMA_FINAL
0,4,Pza. de España,40.423882,-3.712257,0,1.0,0.0,0.0
26,8222,"MADRID, RETIRO",40.411944,-3.678056,0,0.0,1.0,1.0
15,49,Parque del Retiro,40.414444,-3.682500,0,1.0,0.0,0.0
13,47,Mendez Alvaro,40.398099,-3.686814,0,1.0,0.0,0.0
12,40,Vallecas,40.388148,-3.651529,0,1.0,0.0,0.0
10,38,Cuatro Caminos,40.445544,-3.707130,0,1.0,0.0,0.0
9,36,Moratalaz,40.407952,-3.645310,0,1.0,0.0,0.0
8,35,Pza. del Carmen,40.419209,-3.703166,0,1.0,0.0,0.0
14,48,Castellana,40.439890,-3.690373,0,1.0,0.0,0.0
1,8,Escuelas Aguirre,40.421553,-3.682316,0,1.0,0.0,0.0
3,16,Arturo Soria,40.440046,-3.639242,0,1.0,0.0,0.0
2,11,Avda. Ramón y Cajal,40.451473,-3.677349,0,1.0,0.0,0.0
18,55,Urb. Embajada,40.462363,-3.580565,1,1.0,0.0,0.0
25,8221,MADRID AEROPUERTO,40.466667,-3.555556,1,0.0,1.0,1.0
22,59,Juan Carlos I,40.460726,-3.616341,1,1.0,0.0,0.0
7,27,Barajas Pueblo,40.476918,-3.580026,1,1.0,0.0,0.0
17,54,Ensanche de Vallecas,40.373012,-3.612139,1,1.0,0.0,0.0
28,8224,GETAFE,40.299444,-3.722222,2,0.0,1.0,1.0
4,17,Villaverde,40.347147,-3.713317,2,1.0,0.0,0.0
20,57,Sanchinarro,40.494201,-3.660517,3,1.0,0.0,0.0
21,58,El Pardo,40.518070,-3.774610,3,1.0,0.0,0.0
23,60,Tres Olivos,40.500548,-3.689731,3,1.0,0.0,0.0
24,8220,"MADRID, CIUDAD UNIVERSITARIA",40.451667,-3.724167,3,0.0,1.0,1.0
11,39,Barrio del Pilar,40.478232,-3.711536,3,1.0,0.0,0.0
16,50,Plaza Castilla,40.465584,-3.688745,3,1.0,0.0,0.0
27,8223,"MADRID, CUATRO VIENTOS",40.375556,-3.786111,4,0.0,1.0,1.0
19,56,Pza. Elíptica,40.385034,-3.718768,4,1.0,0.0,0.0
5,18,Farolillo,40.394782,-3.731836,4,1.0,0.0,0.0
6,24,Casa de Campo,40.419358,-3.747345,4,1.0,0.0,0.0

## [9.2] - CLUSTERING

In [156]:
df_estaciones_2 = spark.createDataFrame(pd_estaciones_2)
vec_assembler_2 = VectorAssembler(inputCols =["LATITUD","LONGITUD"],outputCol='features')
df_estaciones_2 = vec_assembler_2.transform(df_estaciones_2)

In [157]:
df_estaciones = df_estaciones_2

#SI QUEREMOS ELEGIR UNA K INICIAL (SELECTED_K)
variaciones = []
errores = []
anterior = 0
for i in range(2,df_estaciones.count()):
    kmeans = KMeans(featuresCol='features',k=i,maxIter=30,seed=1)
    df_estaciones_model = kmeans.fit(df_estaciones)
    wssse = df_estaciones_model.computeCost(df_estaciones)
    errores.append(wssse)
    variaciones.append(wssse-anterior)
    anterior = wssse
    #print("K= ",i ," Within Set Sum of Squared Errors = " + str(wssse))

#1 grado == 118 km
#Seleccionamos la k para la cual el error es menor de 1km
i=0
selected_k = -1
for elem in errores:
    distancia = elem*118
    print(i, " - ", distancia)
    if(distancia < 1): 
        selected_k= i 
        break
    i= i+1

In [164]:
selected_k = df_estaciones.count()

#variaciones
errores
#Cuando baja menos que antes
bajada_anterior = 0
selected_k = -1

for i in range(1,len(errores)):
    if((errores[i-1]-errores[i])<bajada_anterior):
        selected_k = i-1
        break
    else:
        bajada_anterior = errores[i]-errores[i-1]
print(selected_k)

In [165]:
df_2 = clustering(selected_k,df_estaciones)

+----------+--------------+---------------------+------+-----------------------+
|prediction|sum(MIDE_AIRE)|sum(MIDE_CLIMA_FINAL)|VALIDO|VALIDO_CON_DESCARTABLES|
+----------+--------------+---------------------+------+-----------------------+
|         0|           2.0|                  1.0|   2.0|                    3.0|
|         1|           3.0|                  1.0|   3.0|                    4.0|
|         2|           2.0|                  1.0|   2.0|                    3.0|
|         4|           2.0|                  1.0|   2.0|                    3.0|
|         5|           1.0|                  1.0|   1.0|                    2.0|
|         6|           1.0|                  1.0|   1.0|                    2.0|
|         9|           2.0|                  4.0|   8.0|                   12.0|
|        10|           2.0|                  2.0|   4.0|                    6.0|
|        11|           1.0|                  1.0|   1.0|                    2.0|
|        12|           2.0|                  2.0|   4.0|                    6.0|
|        13|           2.0|                  3.0|   6.0|                    9.0|
|        14|           2.0|                  2.0|   4.0|                    6.0|
|        16|           2.0|                  2.0|   4.0|                    6.0|
+----------+--------------+---------------------+------+-----------------------+

In [166]:
pd_estaciones_19_NOW = df_2.toPandas()[["CODIGO_CORTO","ESTACION","LATITUD", "LONGITUD","prediction","MIDE_AIRE","MIDE_CLIMA","MIDE_CLIMA_AEMET","MIDE_CLIMA_FINAL"]].sort_values(by="prediction")
pd_estaciones_19_NOW = pd_estaciones_19_NOW.rename(columns={"prediction":"GRUPO"})
pd_estaciones_19_NOW

,CODIGO_CORTO,ESTACION,LATITUD,LONGITUD,GRUPO,MIDE_AIRE,MIDE_CLIMA,MIDE_CLIMA_AEMET,MIDE_CLIMA_FINAL
0,4,Pza. de España,40.423882,-3.712257,0,1.0,0.0,0.0,0.0
29,110,J.M.D.Centro,40.415600,-3.710792,0,0.0,1.0,0.0,1.0
8,35,Pza. del Carmen,40.419209,-3.703166,0,1.0,0.0,0.0,0.0
2,11,Avda. Ramón y Cajal,40.451473,-3.677349,1,1.0,0.0,0.0,0.0
26,107,J.M.D. Hortaleza,40.462778,-3.656667,1,0.0,1.0,0.0,1.0
20,57,Sanchinarro,40.494201,-3.660517,1,1.0,0.0,0.0,0.0
16,50,Plaza Castilla,40.465584,-3.688745,1,1.0,0.0,0.0,0.0
35,8221,MADRID AEROPUERTO,40.466667,-3.555556,2,0.0,0.0,1.0,1.0
18,55,Urb. Embajada,40.462363,-3.580565,2,1.0,0.0,0.0,0.0
7,27,Barajas Pueblo,40.476918,-3.580026,2,1.0,0.0,0.0,0.0
10,38,Cuatro Caminos,40.445544,-3.707130,4,1.0,0.0,0.0,0.0
14,48,Castellana,40.439890,-3.690373,4,1.0,0.0,0.0,0.0
28,109,J.M.D.Chamberí,40.431911,-3.696950,4,0.0,1.0,0.0,1.0
17,54,Ensanche de Vallecas,40.373012,-3.612139,5,1.0,1.0,0.0,1.0
21,58,El Pardo,40.518070,-3.774610,6,1.0,1.0,0.0,1.0
9,36,Moratalaz,40.407952,-3.645310,9,1.0,1.0,0.0,1.0
32,113,J.M.D.Vallecas 2,40.396472,-3.666456,9,0.0,1.0,0.0,1.0
12,40,Vallecas,40.388148,-3.651529,9,1.0,0.0,0.0,0.0
31,112,J.M.D.Vallecas 1,40.396472,-3.666456,9,0.0,1.0,0.0,1.0
24,102,J.M.D. Moratalaz,40.399793,-3.635637,9,0.0,1.0,0.0,1.0
3,16,Arturo Soria,40.440046,-3.639242,10,1.0,1.0,0.0,1.0
22,59,Juan Carlos I,40.460726,-3.616341,10,1.0,1.0,0.0,1.0
25,103,J.M.D. Villaverde,40.350628,-3.709525,11,0.0,1.0,0.0,1.0
4,17,Villaverde,40.347147,-3.713317,11,1.0,0.0,0.0,0.0
5,18,Farolillo,40.394782,-3.731836,12,1.0,1.0,0.0,1.0
6,24,Casa de Campo,40.419358,-3.747345,12,1.0,1.0,0.0,1.0
15,49,Parque del Retiro,40.414444,-3.682500,13,1.0,0.0,0.0,0.0
1,8,Escuelas Aguirre,40.421553,-3.682316,13,1.0,1.0,0.0,1.0
30,111,J.M.D.Chamartin,40.422649,-3.680369,13,0.0,1.0,0.0,1.0
36,8222,"MADRID, RETIRO",40.411944,-3.678056,13,0.0,0.0,1.0,1.0
19,56,Pza. Elíptica,40.385034,-3.718768,14,1.0,0.0,0.0,0.0
13,47,Mendez Alvaro,40.398099,-3.686814,14,1.0,0.0,0.0,0.0
33,114,Matadero 01,40.392544,-3.697631,14,0.0,1.0,0.0,1.0
34,115,Matadero 02,40.392544,-3.697631,14,0.0,1.0,0.0,1.0
23,60,Tres Olivos,40.500548,-3.689731,16,1.0,0.0,0.0,0.0
27,108,Peñagrande,40.476633,-3.717881,16,0.0,1.0,0.0,1.0
11,39,Barrio del Pilar,40.478232,-3.711536,16,1.0,1.0,0.0,1.0

## [10.1] - EXPORTAMOS

In [167]:
pd_estaciones_14_18.to_csv("/home/rulicering/Datos_Proyecto_Ozono/Procesado/Versiones/Estaciones/[v1]-Estaciones_14_18.csv")

## [10.2] - EXPORTAMOS

In [168]:
pd_estaciones_19_NOW.to_csv("/home/rulicering/Datos_Proyecto_Ozono/Procesado/Estaciones/[v1]-Estaciones/Estaciones_19_NOW.csv")